---
# Suggested tools that can save round-trips to github and a lot of time:
#
# yamllint .travis.yml
# ~/.gem/ruby/2.7.0/bin/travis lint .travis.yml
# yaml merge-expand .travis.yml exp.yml && diff -b -u .travis.yml exp.yml


# focal = 2020
dist: focal

language: minimal

git:
  depth: false
  quiet: true

before_install:
  - sudo apt-get -y install shellcheck pylint

jobs:
  include:

    - name: "shellcheck"
      # Triple-dotted 'origin/master...HEAD'
      script: ./tools/CI/check-gitrange.bash "${TRAVIS_COMMIT_RANGE}"
        text/x-shellscript shellcheck -x

    - name: "pylint"
      # let's re-enable 'C'onventions once we got the other numbers down
      script: ./tools/CI/check-gitrange.bash "${TRAVIS_COMMIT_RANGE}"
        text/x-python pylint --disable=C
